#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d  home web dev music mail chat game

bspc config border_width         1
bspc config window_gap          0

bspc config focused_border_color \#7F9F7F
bspc config normal_border_color \#494949
bspc config border_radius 0


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#autostart programs
xwallpaper --stretch ~/Multimedia/Pictures/Wallpaper/zenbum.png
$HOME/.config/polybar/launch.sh &
picom

